[package]
name = "logger"
authors = ["The HugoByte Team <hello@hugobyte.com>"]
edition = "2021"
repository = "https://github.com/hugobyte/aurras.git"
version = "0.0.1"

[dependencies]
log = "0.4.21"
env_logger =  "0.11.3"